channels:
- conda-forge
- nodefaults
dependencies:
- make
- mypy
- pip
- pre-commit
- pytest
- pytest-cov
- postgresql
- psycopg
- psycopg2
- sqlalchemy==1.4*
- sqlalchemy-stubs
- typer
- pip:
  - pytest-postgresql
  - git+https://github.com/ecmwf-projects/ogc-api-processes-fastapi.git@e39093d807b170f3f403716ba0beca989b7684fb
