channels:
- conda-forge
- nodefaults
dependencies:
- dask
- distributed
- make
- pip
- pre-commit
- postgresql
- psycopg
- psycopg2
- pydantic
- pytest
- pytest-cov
- pytest-mock
- sqlalchemy==1.4*
- sqlalchemy-utils
- sqlalchemy-stubs
- tornado==6.1
- typer
- uvicorn
- pip:
  - pytest-postgresql
  - git+https://github.com/ecmwf-projects/ogc-api-processes-fastapi.git
  - types-sqlalchemy-utils
